version: '3.8'

services:
    db:
        image: postgres
        container_name: postgres-db-container
        restart: always
        environment:
            POSTGRES_USER: sat
            POSTGRES_PASSWORD: sat1234
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - local_pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: heart@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    local_pgdata:
    pgadmin-data:
